<a href="https://colab.research.google.com/github/IM-RAHUL-RAJ/py_pandas_datascience/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***NUMPY***

In [1]:
import numpy as np

In [2]:
myarr=np.array([3,6,32,7])

In [3]:
print(myarr)

[ 3  6 32  7]


In [4]:
print(type(myarr))

<class 'numpy.ndarray'>


In [12]:
myarr=np.array([[3,6,32333,7]],np.int8)

In [13]:
myarr

array([[ 3,  6, 77,  7]], dtype=int8)

In [14]:
myarr[0,2]

77

In [15]:
myarr.shape

(1, 4)

In [16]:
myarr.dtype

dtype('int8')

In [17]:
type(myarr)

numpy.ndarray

In [19]:
myarr[0,1]=45

In [20]:
myarr

array([[ 3, 45, 77,  7]], dtype=int8)

In [21]:
print(myarr)

[[ 3 45 77  7]]


In [2]:
import numpy as np
listarray=np.array([[1,2,3],[4,5,6],[7,0,1]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [3]:
listarray.dtype

dtype('int64')

In [4]:
listarray.shape

(3, 3)

In [5]:
listarray.size

9

In [7]:
zeros=np.zeros((2,5))

In [8]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
zeros.shape

(2, 5)

In [10]:
zeros.dtype

dtype('float64')

In [11]:
type(zeros)

numpy.ndarray

In [12]:
range=np.arange(15)

In [13]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
lspace=np.linspace(1,5,12)

In [15]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [17]:
lspace2=np.linspace(1,10,4)
lspace2

array([ 1.,  4.,  7., 10.])

In [25]:
emp=np.empty((3,5))



In [26]:
emp




array([[0.00000000e+000, 1.01855798e-312, 1.03977794e-312,
        9.54898106e-313, 1.16709769e-312],
       [1.06099790e-312, 1.23075756e-312, 1.03977794e-312,
        1.12465777e-312, 9.76118064e-313],
       [1.14587773e-312, 1.08221785e-312, 1.12465777e-312,
        2.22809558e-312, 2.14321575e-312]])

In [27]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(45, 45)

In [37]:
a=np.arange(99)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
a.reshape(3,33)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
listarray.sum(axis=0)

array([12,  7, 10])

In [43]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [44]:
listarray.sum(axis=1)

array([ 6, 15,  8])

In [45]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [46]:
listarray.T

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [47]:
listarray.ndim

2

In [49]:
import pandas as pd

listarray2=pd.DataFrame(listarray)
listarray2

0  1  2
0  1  2  3
1  4  5  6
2  7  0  1

In [50]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
randomarray=np.random.randint(0,10,size=(3,5))
randomarray

array([[1, 1, 4, 6, 6],
       [3, 4, 0, 5, 0],
       [5, 2, 9, 7, 0]])

In [53]:
randomarray=np.random.randint(0,10)
randomarray

7

In [56]:
randomarray.size

15

In [57]:
randomarray.shape

(3, 5)

In [60]:
randomarray2=np.random.random((3,5))
randomarray2

array([[0.49243987, 0.77508726, 0.59567283, 0.29905941, 0.73701933],
       [0.93263717, 0.14721751, 0.89472708, 0.95804875, 0.48011446],
       [0.58280569, 0.83939473, 0.72163105, 0.34369325, 0.28339331]])

In [62]:
randomarray3=np.random.randint(10,size=(2,3))
randomarray3

array([[6, 1, 5],
       [4, 4, 6]])

In [64]:
np.unique(randomarray3)

array([1, 4, 5, 6])

In [67]:
randomarray4=np.random.randint(10,size=(2,3,4,5))
randomarray4

array([[[[9, 3, 6, 4, 3],
         [0, 4, 4, 0, 5],
         [7, 0, 4, 0, 8],
         [1, 4, 1, 5, 7]],

        [[6, 9, 7, 8, 9],
         [7, 1, 5, 6, 1],
         [3, 4, 5, 0, 6],
         [4, 8, 4, 1, 1]],

        [[6, 1, 8, 8, 6],
         [5, 9, 4, 2, 8],
         [5, 1, 9, 5, 1],
         [1, 5, 6, 7, 8]]],


       [[[1, 2, 3, 1, 7],
         [8, 4, 2, 5, 4],
         [0, 3, 1, 1, 2],
         [6, 9, 3, 7, 5]],

        [[6, 3, 6, 4, 4],
         [2, 6, 6, 9, 4],
         [1, 3, 4, 0, 4],
         [6, 1, 0, 9, 9]],

        [[4, 7, 5, 5, 3],
         [5, 4, 7, 9, 4],
         [1, 0, 4, 0, 0],
         [1, 2, 7, 0, 9]]]])

In [68]:
randomarray4.shape

(2, 3, 4, 5)

In [69]:
a1=np.array([2,3,4])
a2=np.array([3,4,5])
a1*a2

array([ 6, 12, 20])

In [70]:
np.square(a1)

array([ 4,  9, 16])

In [72]:
np.add(a1,a2)

array([5, 7, 9])

In [73]:
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [74]:
a1%2

array([0, 1, 0])

In [75]:
a1*a2

array([ 6, 12, 20])

In [77]:
a3=np.dot(a1,a2)

In [78]:
a3

38

In [82]:
np.random.seed(0)
sales=np.random.randint(-2,20,size=(5,3))
sales

array([[10, 13, 19],
       [-2,  1,  1],
       [ 5,  7, 17],
       [19, 16,  2],
       [ 4, 10, -1]])

In [4]:
import numpy as np
a5=np.array([[1,2,3],[4,5,6]])
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a5.flat #these are attributes

In [6]:
a5.nbytes

48

In [8]:
a5.argmax()  #with paranthesis its method

5

In [13]:
a5.argmin()  #returns index

0

In [12]:
a5.argsort()

array([[0, 1, 2],
       [0, 1, 2]])

In [14]:
[324,34]+[333,33]  #lists in python

[324, 34, 333, 33]

In [16]:
a5.max(),a5.min(),a5.sum()

(6, 1, 21)

In [17]:
np.where(a5>3)

(array([1, 1, 1]), array([0, 1, 2]))

In [18]:
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.count_nonzero(a5)

6

In [20]:
np.nonzero(a5)

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))

In [21]:
import sys

In [22]:
py_ar=[0,4,5,6]


In [23]:
np_ar=np.array(py_ar)

In [24]:
np_ar

array([0, 4, 5, 6])

In [26]:
np_ar.nbytes  #numpy array takes less size

32

In [27]:
py_ar

[0, 4, 5, 6]

In [29]:
sys.getsizeof(1)*len(py_ar)   #python array size

112